### ISSUE TITLE
Python 3 compatible version of ISYlib-python package

### ISSUE THREAD

**Issue by fxstein** [fxstein/ISYlib-python#1]
TO: @evilpete @Robert-Nelson @firegood @sjthespian @copart

As I was in the need for a Python 3 compatible version of the ISYlib-python package I looked through all the forks and branches and ultimately merged all of them (to the best of my knowledge) into my fork and applied a few more fixes along the way. I have it now up and running with Python 3 (Mac/homebrew).

Let me know if you want me to create a pull request into the original repo or just leave this fork as is. 

FYI - Some background

I am using this (and other libraries) as part of my Sentient Home project that feeds realtime data from any source (inside and outside the home) into a realtime event engine as well as a realtime time series database (influxdb for now) to store and process events with very simple all-python based event feeders and rules. It is work in progress and I have not really shared it with anybody due to its infancy.

**Comment by evilpete** [comment]
Thanks I'll take a look. There have been a few requests for Py3 support.
( I'm also happy to see others contribute, as I feel a project like this
shouldn't be a one man band )

**Comment by fxstein** [comment]
Since there has been no further messages on this I am closing this issue. Have been using this Python 3 version of ISYlib for months. Working great for me.

**Comment by evilpete** [comment]
I'm looking for people to co-maintain ISYlib are you interested? At least
on a trial basis.

I clearly do not have the time if I want to spend any significant time on
any other projects.

**Comment by fxstein** [comment]
Peter,

I understand. Time is at a premium for all of us. I too am very busy, but just happen to need a working Py3 ISY library as I am streaming ISY event in realtime into an analytics engine and time series database.

This is a hobby for me to keep my programming skills in shape as my job has moved well beyond programming for the most parts.

Happy to help in any way I can but it will be spotty too.

On that note there is another project that surfaced: pyISY

Would it be smart to combine efforts?

It too needs a bunch of help as the author has not spent much time on the likes of PEP8 or extensibility.

Oliver

**Comment by evilpete** [comment]
i have no problem with giving others commit authorization, as long as 2.7
compatibility is maintained.

I've seen the pyISY lib, it seemed to be focused on callback functionality,
i assume the author wrote it not realizing my libraries already supported
that functionality
